version: "3.9"
services:
  proxy:
    build: .
    ports:
      - "8080:8080"
  api:
    build: _api
    environment:
      - USERNAME=tristan
      - PASSWORD=secretPassword
    ports:
      - "8080"